services:
  - type: web
    name: fc-ymt-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /api/ymt/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
